apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: three-tier
spec:
  type: NodePort
  selector:
    role: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
